version: 2.1

orbs:
  maven: circleci/maven@0.0.12

build:
  environment:
    # Customize the JVM maximum heap limit
    MAVEN_OPTS: "-Xmx8G"
    JAVA_OPTS: "-Xms8G -Xmx8G"

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
